# Generated by Django 4.2.4 on 2023-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('car_brand', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
