# Generated by Django 4.2.4 on 2023-09-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vehicles_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='description',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='fuel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
