# Generated by Django 4.2.4 on 2023-10-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_order_endrent_alter_order_startrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='endRent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='startRent',
            field=models.TextField(null=True),
        ),
    ]
