# Generated by Django 4.2.4 on 2023-10-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_order_endrent_alter_order_startrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='price_per_day',
        ),
    ]
