# Generated by Django 4.2.4 on 2023-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_price_order_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='endRent',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='startRent',
            field=models.DateField(null=True),
        ),
    ]
