# Generated by Django 4.2.4 on 2023-10-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_customer_phone_order_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicles'),
        ),
    ]
