# Generated by Django 4.2.4 on 2023-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_order_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
